  on:
    push:
      branches:
        - masterr

  jobs:
    build:
      runs-on:  ubuntu-latest

      steps:
        - name: 'Before printing folder Contents'
          run: ls

        - uses: actions/checkout@v3
        - name: 'After printing folder Contents'
          run: ls 

