  on:
    push:
      branches:
        - masterr

  jobs:
    build:
      runs-on:  ubuntu-latest

      steps:
        - name: 'Before printing folder Contents'
          run: ls

        - uses: actions/checkout@v3
        - name: 'Login to docker hub'
          run: docker login --username marwagamal5 --password dckr_pat_ZyETbguS94pyZCO5-M272fCPQCY  

