  on:
    push:
      branches:
        - masterr

  jobs:
    build:
      runs-on:  ubuntu-latest

      steps:
        - name: 'Before printing folder Contents'
          run: ls

        - uses: actions/checkout@v3
        - name: 'Login to docker hub'
          run: docker login --username ${{ secrets.MEROO }} --password ${{ secrets.TOKENNAME }}  

